# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [27]:
import pandas as pd

df = pd.read_csv("../../data/students.csv")
df.head()

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
2,Charlie,Brown,78,82,80.0,B,7,83
3,David,Wilson,92,95,93.5,A,5,97

### 🔢 2. Sorting Data

In [28]:
# Sort by math_score
df.sort_values(by="MATH")

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
2,Charlie,Brown,78,82,80.0,B,7,83
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
3,David,Wilson,92,95,93.5,A,5,97

In [29]:
# Sort by science_score descending
df.sort_values(by="SCIENCE", ascending=False)

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
3,David,Wilson,92,95,93.5,A,5,97
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
2,Charlie,Brown,78,82,80.0,B,7,83

In [30]:
# Sort by multiple columns
df.sort_values(by=["SCIENCE", "MATH"], ascending=[False, True])

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
3,David,Wilson,92,95,93.5,A,5,97
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
2,Charlie,Brown,78,82,80.0,B,7,83

### 🧪 3. Filtering with Conditions

In [31]:
# Who scored at least 90 in math?
df[df["MATH"] >= 90]

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
1,Bob,Jones,90,85,87.5,B,3,95
3,David,Wilson,92,95,93.5,A,5,97

In [32]:
# Who scored less than 70 in either subject?
df[(df["MATH"] < 70) | (df["SCIENCE"] < 70)]

Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, MATH, SCIENCE, AVERAGE_SCORE, GRADE, NAME_LENGTH, MATH_PLUS_5]
Index: []

### 🔗 4. Combining Filters

In [33]:
# Students with B+ or higher in both
df[(df["MATH"] >= 87) & (df["SCIENCE"] >= 87)]

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
3,David,Wilson,92,95,93.5,A,5,97

### 🧾 5. Using `.query()` for Readability

In [34]:
# Same query using .query()
df.query("MATH >= 87 and SCIENCE >= 87")

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
3,David,Wilson,92,95,93.5,A,5,97

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [35]:
# Sort by first name alphabetically
print("Sorted by first name:")
print(df.sort_values(by="FIRST_NAME"))

# Find students with the same math and science score
print("\nSame math and science score:")
print(df[df["MATH"] == df["SCIENCE"]])

# Use query to find students who scored over 95 in either subject
print("\nScored over 95 in either subject:")
print(df.query("MATH > 95 or SCIENCE > 95"))

Sorted by first name:
  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE  NAME_LENGTH  \
0      Alice     Smith    85       88           86.5     B            5
1        Bob     Jones    90       85           87.5     B            3
2    Charlie     Brown    78       82           80.0     B            7
3      David    Wilson    92       95           93.5     A            5

   MATH_PLUS_5
0           90
1           95
2           83
3           97

Same math and science score:
Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, MATH, SCIENCE, AVERAGE_SCORE, GRADE, NAME_LENGTH, MATH_PLUS_5]
Index: []

Scored over 95 in either subject:
Empty DataFrame
Columns: [FIRST_NAME, LAST_NAME, MATH, SCIENCE, AVERAGE_SCORE, GRADE, NAME_LENGTH, MATH_PLUS_5]
Index: []

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [36]:
import pandas as pd

# Load survey dataset
survey = pd.read_csv("../../data/survey.csv")

# Sort by most recent survey date
survey["survey_date"] = pd.to_datetime(
    survey["survey_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

survey = survey.sort_values(by="survey_date", ascending=False)

# Replace N/A with missing values
survey = survey.replace("N/A", pd.NA)

# Remove incomplete rows
survey_clean = survey.dropna()

# Query students with GPA over 3.5
result = survey_clean.query("gpa > 3.5")

print("Cleaned Survey Data:")
print(survey_clean.head())

print("\nQuery Result:")
print(result.head())

Cleaned Survey Data:
Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []

Query Result:
Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |