# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [15]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [16]:
import pandas as pd

data = """Name,Age,Score
Manoj,21,95
Alex,22,88
Sam,20,91
"""

with open("my_students.csv", "w") as f:
    f.write(data)

df = pd.read_csv("my_students.csv")

df

    Name  Age  Score
0  Manoj   21     95
1   Alex   22     88
2    Sam   20     91

## 2. Exploring DataFrames

In [17]:
# Look at the first rows
df.head()

    Name  Age  Score
0  Manoj   21     95
1   Alex   22     88
2    Sam   20     91

In [18]:
# Info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Score   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [19]:
# Summary statistics
df.describe()

        Age      Score
count   3.0   3.000000
mean   21.0  91.333333
std     1.0   3.511885
min    20.0  88.000000
25%    20.5  89.500000
50%    21.0  91.000000
75%    21.5  93.000000
max    22.0  95.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [20]:
df.head()

    Name  Age  Score
0  Manoj   21     95
1   Alex   22     88
2    Sam   20     91

In [21]:
df.describe()

        Age      Score
count   3.0   3.000000
mean   21.0  91.333333
std     1.0   3.511885
min    20.0  88.000000
25%    20.5  89.500000
50%    21.0  91.000000
75%    21.5  93.000000
max    22.0  95.000000

## 3. Writing CSV Files

In [22]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

my_data.csv        my_students.csv    students.csv       students_copy.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [23]:
df.to_csv("my_data.csv", index=False)

%ls *.csv

my_data.csv        my_students.csv    students.csv       students_copy.csv

## 4. Reading Excel Files

In [24]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

    Name  Age  Score
0  Manoj   21     95
1   Alex   22     88
2    Sam   20     91

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [25]:
df.to_excel("students.xlsx", index=False)

pd.read_excel("students.xlsx")

    Name  Age  Score
0  Manoj   21     95
1   Alex   22     88
2    Sam   20     91

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.